### ISSUE TITLE
How to use version in catalog.yml?

### ISSUE THREAD

**Issue by KirjanovIlja** [getindata/kedro-azureml#184]
Hello, 

We use kedro_azureml.datasets.AzureMLAssetDataset in catalog.yaml, by default latest version of dataset is loaded but we need a specific one. 

Based on [documentation](https://github.com/getindata/kedro-azureml/blob/0.8.0/kedro_azureml/datasets/asset_dataset.py) we should be able to specify by _**version**_ key. But it does not work, as we get: 

`WARNING: 'version' attribute removed from data set configuration since it is a reserved word and cannot be directly specified`

How to reproduce: 

requirements.txt
```
kedro-azureml==0.8.0
kedro==0.18.14
```

catalog.yaml
```
some_dataset:
  type: kedro_azureml.datasets.AzureMLAssetDataset
  azureml_dataset: my-dataset-from-azureml
  version: 100
  root_dir: data/01_raw/some_data
  dataset:
    type: pandas.ParqueDataset
    filepath: .
```

Please advise on how to specify properly the version to not get only the latest one. 

Thanks in advance
