### ISSUE TITLE
AzureMLPipelineDataSet preview of CSV does not work

### ISSUE THREAD

**Issue by marrrcin** [getindata/kedro-azureml#57]
@tomasvanpottelbergh this is related to the `AzureMLPipelineDataSet` you've implemented.

---
## Issue
When saving intermediate data as `pandas.CSV` with **pipeline_data_passing** feature enabled, the data is indeed saved properly, but the preview does not work - it shows up as a base64-encoded blob (See the screenshot).
I'm suspecting that something has changed in the Azure's SDK that ends up with the file being recognized as blob rather that CSV.

Entry in the catalog I'm using:
```yaml
preprocessed_shuttles:
  type: kedro_azureml.datasets.AzureMLPipelineDataSet
  dataset:
    type: pandas.CSVDataSet
    filepath: "shuttles.csv"
```

Preview:
![image](https://user-images.githubusercontent.com/6958772/235166299-17913a48-b70c-4476-947a-6d583aeca1c5.png)
