### ISSUE TITLE
Pipeline failing when using MlflowModelLoggerDataSet as an input of a node

### ISSUE THREAD

**Issue by Gabriel2409** [getindata/kedro-azureml#63]
I noticed a small issue when integrating with kedro-mlflow, more specifically with kedro_mlflow.io.models.MlflowModelLoggerDataSet when we want to reuse them from one node to another. 

Consider the following scenario: 

```yml
#catalog.yml
mlflow_logger_model:
  type: kedro_mlflow.io.models.MlflowModelLoggerDataSet
  flavor: mlflow.sklearn
````

```python
# node.py
import numpy as np

from sklearn.dummy import DummyClassifier
def create_mlflow_model_artifact():
    X = np.array([[1],[2]])
    y = np.array([0,1])
    model = DummyClassifier()
    model.fit(X,y)
    return model 

def dummy_predict(model):
    X = np.array([[1],[2]])
    model.predict(X)
```

```python 
#pipeline.py
from kedro.pipeline import Pipeline, node
from .nodes import dummy_predict, create_mlflow_model_artifact


def create_pipeline(**kwargs) -> Pipeline:
    return Pipeline(
        nodes=[
            node(
                func=create_mlflow_model_artifact,
                inputs=None,
                outputs="mlflow_logger_model",
                name="create_mlflow_model_artifact",
            ),
            node(
                func=dummy_predict,
                inputs="mlflow_logger_model",
                outputs=None,
                name="dummy_predict",
            ),
        ]
    )
```

In this scenario, the dummy classifier is logged to mlflow but can not be used by the second node dummy_predict

![image](https://github.com/getindata/kedro-azureml/assets/12717469/133145e4-67e7-473d-a3a3-de35df6c369b)

```
DatasetError: Failed while loading data from data set 
MlflowModelLoggerDataSet(artifact_path=model, flavor=mlflow.sklearn, 
load_args={}, save_args={}).
The following failures occurred while downloading one or more artifacts from 
................
```

We could save the model as an MlflowArtifactDataSet and provide a path instead: 
```yml
#catalog.yml
mlflow_logger_model:
    type: kedro_mlflow.io.artifacts.MlflowArtifactDataSet
    data_set:
        type: kedro_mlflow.io.models.MlflowModelSaverDataSet
        flavor: mlflow.sklearn
        filepath: data/06_models/sklearn_model
````
It worked when I launched the pipeline with this configuration. However I suspect it only worked because I had first ran the pipeline locally and the sklearn_model folder existed on my local machine before launching the pipeline. 

Maybe the best way is to consider that everything that is tracked by mlflow should not be reused as an input in the pipeline.

**Comment by marrrcin** [comment]
Hi, thanks for creating the issue!

Are you using external MLflow instance or the one that is built-in in the AML Workspace?

If you're using the built-in MLflow, as a temporary workaround before we dive into debugging, you can actually use `kedro-azureml` without `kedro-mlflow` and call `mlflow.<framework>.log_model` and all other MLflow's functions without any restrictions. AML workspace injects appropriate MLflow environment variables automatically into nodes, so you don't have to set anything on your own. Remember to install the plugin with `kedro-azureml[mlflow]` extra.

**Comment by Gabriel2409** [comment]
Hi Marcin, thanks for your reply. 

After further investigation, I don't think the issue comes from MLFlow. 

In fact, in my example above, if I don't specify `mlflow_logger_model` in `catalog.yml`, it is passed between nodes as a MemoryDataset and the pipeline succeeds. 

However,  if I explicitely pass the model as a pickle dataset
```yml
#catalog.yml
mlflow_logger_model:
    type: pickle.PickleDataSet
    filepath: mymodel.pkl
```
then the pipeline fails
```
DatasetError: Failed while loading data from data set 
PickleDataSet(backend=pickle, 
filepath=/mnt/azureml/cr/j/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/exe/wd/mymodel.pkl, 
load_args={}, protocol=file, save_args={}).
[Errno 2] No such file or directory: 
'/mnt/azureml/cr/j/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/exe/wd/mymodel.pkl'
```
Saving the model seems to succeed but loading it in the next node fails.

**Comment by marrrcin** [comment]
If you're using AzureML, there is no concept of local paths there - saving your model to `filepath: mymodel.pkl` will save this file ONLY in the node that created it. Next node - in your case - the one that should consume the pickle - has completely separate file system - there are no shared volumes between the nodes in AzureML. 
If you want to pass data between the models you have the following options:
1. Use `fsspec`-compatible path and save the data to Azure Blob Storage (this works will most if not all Kedro datasets). See https://docs.kedro.org/en/stable/data/data_catalog.html#specify-the-location-of-the-dataset
```yaml
mlflow_logger_model:
    type: pickle.PickleDataSet
    filepath: abfs://<your storage container>/mymodel.pkl
```
2. Use recently released `AzureMLAssetDataSet` (it's available in `0.5.0`) https://kedro-azureml.readthedocs.io/en/0.5.0/source/05_data_assets.html#kedro_azureml.datasets.asset_dataset.AzureMLAssetDataSet
```yaml
mlflow_logger_model:
  type: kedro_azureml.datasets.AzureMLAssetDataSet
  azureml_dataset: my_model
  root_dir: data
  versioned: True
  dataset:
    type: pickle.PickleDataSet
    filepath: mymodel.pkl
```
