### ISSUE TITLE
Proper way to persist interpolations

### ISSUE THREAD

**Issue by Dekermanjian** [getindata/kedro-azureml#89]
@marrrcin I am opening up this ticket as a follow-up to ticket #88 

I was able to follow your helpful instructions and got the pipeline from Azure DevOps running. The issue I am having now is that while the pipeline will send the kedro pipeline to Azure ML. The interpolations using `oc.env` do not persist in Azure ML and hence the pipeline will fail. 
This is what my azureml.yml looks like:
```
azure:
  # Azure subscription ID to use
  subscription_id: ${oc.env:AZURE_SUBSCRIPTION_ID}
  # Azure ML Experiment Name
  experiment_name: "kedro_azml"
  # Azure resource group to use
  resource_group: ${oc.env:AZURE_RESOURCE_GROUP}
  # Azure ML Workspace name
  workspace_name: ${oc.env:AZURE_WORKSPACE_NAME}
  # Azure ML Environment to use during pipeline execution
  environment_name: ~
  # Path to directory to upload, or null to disable code upload
  code_directory: ~
```

Where the environment variables are set in the Azure DevOps Pipeline.
Again, the pipeline succeeds and sends the job to Azure ML. However, those environment variables are not persisted so in Azure ML the job fails:
![image](https://github.com/getindata/kedro-azureml/assets/39779176/6d1bc224-d7eb-44a4-b7e4-4210d6ec285a)

Should I be setting these variables in the docker image itself or on the compute cluster somehow or something else?
Any help will be very appreciated.

**Comment by marrrcin** [comment]
Hi @Dekermanjian ,
you only need those environment variables during the pipeline generation on the DevOps side, after the pipeline reaches the Azure ML workspace, the environment variables in `azureml.yml` are mostly not needed as far as I remember. Our config usually looked like this:

```yaml
azure:
  # Azure subscription ID to use
  subscription_id: "${oc.env:AZURE_SUBSCRIPTION_ID,''}"
  # Azure ML Experiment Name
  experiment_name: "kedro_azml"
  # Azure resource group to use
  resource_group: "${oc.env:AZURE_RESOURCE_GROUP,''}"
  # Azure ML Workspace name
  workspace_name: "${oc.env:AZURE_WORKSPACE_NAME,''}"
  # Azure ML Environment to use during pipeline execution
  environment_name: ~
  # Path to directory to upload, or null to disable code upload
  code_directory: ~

```
